ionice & nice added to mysqldump to fix high cpu resource issue
databacker/mysql-backup pull request #148
Opened 2020-11-12 15:54 UTC by Anishmourya

Signed-off-by: Anish Dhanka <anish.mourya5@gmail.com>

2020-11-13 08:39 UTC, deitch requested changes
Thanks for this, looks good. A few changes, and we will be good to go.

2020-11-13 08:39 UTC, deitch commented on CONTRIBUTORS.md
> +* Anish Dhanka <https://github.com/anishmourya>
Please remove the extra line between Luke and you.

2020-11-13 08:39 UTC, deitch commented on functions.sh
> +      if [[ $NICE ]]; then
Since you documented it as `true`, let's make this:

```sh
if [ "$NICE" = "true" ]; then
```

2020-11-13 08:39 UTC, deitch commented on functions.sh
> +      if [[ $NICE ]]; then
The line is repetitive here, so let's make it cleaner:

```sh
NICE_CMD=
if [ "$NICE" = "true" ]; then
   NICE_CMD="nice -n19 ionice -c2"
fi
$NICE_CMD mysqldump -h ...
```

2020-11-13 08:39 UTC, deitch commented on functions.sh
> +    fi
Same comments as for the above mysqldump command.

2020-11-17 20:13 UTC, Anishmourya commented
@deitch thanks for pr review. I have updated according to your comments. let me know if I need to change something else. thanks

2020-11-18 11:17 UTC, deitch approved these changes
Thanks!

2020-11-18 11:17 UTC, merged